### ISSUE TITLE
Installing issue on Homey

### ISSUE THREAD

**Issue by magtimmermans** [nattlip/com.jilles.plugwisesource#3]
Hi,

I tried to install:

D:\homey>athom project --run com.jilles.plugwisesource-master
{ code: 400,
  error: 'invalid_grant',
  error_description: 'Invalid refresh token' }

Gives an error.

**Comment by nattlip** [comment]
you must leave the master : no '-master'  it is 

D:\homey>athom project --run com.jilles.plugwisesource

which version are you using .  if 0.8.34 then change 
in app.js line 289
  checkpath = path.substring(0, 4);  to   checkpath = path.substring(0, 5);

**Comment by magtimmermans** [comment]
Hi,
Unfortunately it didn't work. I still get:

D:\homey>athom project --run com.jilles.plugwisesource
{ code: 400,
  error: 'invalid_grant',
  error_description: 'Invalid refresh token' }

**Comment by nattlip** [comment]
you must be with the node command window in the directory where com.jilles.plugwisesource is a child and then athom project --run without any token or name

**Comment by magtimmermans** [comment]
Thanks. This is working now

**Comment by gruijter** [comment]
Just instaled it, but I'm getting a crash when I test the webserver connection.

```Hello world init app.js
Hello world
app 25  plugiseserverset value : false
value ip setting input box undefined
value port setting input box undefined
value user setting input box undefined
value password  setting input box undefined
value testing setting false
99 plugwiseserverconnected  false
plugwiseservertested  false
app 102  check if server is set    server is notset
entered Homey.manager(settings).on(set, function (testing)
function (plugwiseservertested)the variable false
 156 testing  false
app 162 setting value of key serverip : undefined
app 146 testing : undefined
153 self.plugwiseservertested  false
app init 157init test
driver 19 init driver
no device data
driver 32  plugiseserverset value : false
app 19 polleri before 1
pollplugwise  self.plugwiseserverset false
pollplugwise  self.testplugwiseserver false
pollplugwise  self.plugwiseserverconnected false
app 27 polleri after  1
181 settings on set with serverip  undefined
 before req to be executed options2   { host: undefined,
  port: undefined,
  path: '/statistics.xml',
  method: 'GET',
  auth: 'undefined:undefined' }
181 settings saved on index
driver 174  callback2 entered
app 50         response on end
app 231    before   if (self.plugwiseservertested)       false
app 232   befor   if (response.statusCode == 200)       404
app 233   before    if (!self.plugwiseserverconnected)       true
app 237    after   if (self.plugwiseservertesting)       true
/api/  checkpath =  /stat
!(checkpath == /api/) true
driver 469  processdevcedata entered
TypeError: Cannot read property 'items' of undefined
    at /drivers/circle/driver.js:272:34
    at Parser.<anonymous> (/node_modules/xml2js/lib/xml2js.js:265:20)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.saxParser.onerror (/node_modules/xml2js/lib/xml2js.js:109:24)
    at emit (/node_modules/xml2js/node_modules/sax/lib/sax.js:615:33)
    at error (/node_modules/xml2js/node_modules/sax/lib/sax.js:644:3)
    at strictFail (/node_modules/xml2js/node_modules/sax/lib/sax.js:662:22)
    at Object.write (/node_modules/xml2js/node_modules/sax/lib/sax.js:934:11)
    at Parser.exports.Parser.Parser.parseString (/node_modules/xml2js/lib/xml2js.js:273:29)

--- INFO: com.jilles.plugwisesource has been killed ---```

I'm on firmware 0.9.3. The source webserver is running correctly, and is reachable from the network.

EDIT: If I do not test the server settings, but just save them directly the app does not crash and I can pair the devices without problem.

**Comment by nattlip** [comment]
@gruijter : new version , the testing server bug should be over.

**Comment by bvdbos** [comment]
This was fixed, bug #4 is something else ?
